/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthSignUpRouteImport } from './routes/auth.sign-up'
import { Route as AuthSignInRouteImport } from './routes/auth.sign-in'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth.forgot-password'
import { Route as AppSkillsRouteImport } from './routes/app.skills'
import { Route as AppRoadmapRouteImport } from './routes/app.roadmap'
import { Route as AppReadinessRouteImport } from './routes/app.readiness'
import { Route as AppMentorRouteImport } from './routes/app.mentor'
import { Route as AppInterviewRouteImport } from './routes/app.interview'
import { Route as AppGamificationRouteImport } from './routes/app.gamification'
import { Route as AppDashboardRouteImport } from './routes/app.dashboard'
import { Route as AppAdminRouteImport } from './routes/app.admin'

const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/auth/sign-up',
  path: '/auth/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/auth/sign-in',
  path: '/auth/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/auth/forgot-password',
  path: '/auth/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSkillsRoute = AppSkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => AppRoute,
} as any)
const AppRoadmapRoute = AppRoadmapRouteImport.update({
  id: '/roadmap',
  path: '/roadmap',
  getParentRoute: () => AppRoute,
} as any)
const AppReadinessRoute = AppReadinessRouteImport.update({
  id: '/readiness',
  path: '/readiness',
  getParentRoute: () => AppRoute,
} as any)
const AppMentorRoute = AppMentorRouteImport.update({
  id: '/mentor',
  path: '/mentor',
  getParentRoute: () => AppRoute,
} as any)
const AppInterviewRoute = AppInterviewRouteImport.update({
  id: '/interview',
  path: '/interview',
  getParentRoute: () => AppRoute,
} as any)
const AppGamificationRoute = AppGamificationRouteImport.update({
  id: '/gamification',
  path: '/gamification',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/admin': typeof AppAdminRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/gamification': typeof AppGamificationRoute
  '/app/interview': typeof AppInterviewRoute
  '/app/mentor': typeof AppMentorRoute
  '/app/readiness': typeof AppReadinessRoute
  '/app/roadmap': typeof AppRoadmapRoute
  '/app/skills': typeof AppSkillsRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/admin': typeof AppAdminRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/gamification': typeof AppGamificationRoute
  '/app/interview': typeof AppInterviewRoute
  '/app/mentor': typeof AppMentorRoute
  '/app/readiness': typeof AppReadinessRoute
  '/app/roadmap': typeof AppRoadmapRoute
  '/app/skills': typeof AppSkillsRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/admin': typeof AppAdminRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/gamification': typeof AppGamificationRoute
  '/app/interview': typeof AppInterviewRoute
  '/app/mentor': typeof AppMentorRoute
  '/app/readiness': typeof AppReadinessRoute
  '/app/roadmap': typeof AppRoadmapRoute
  '/app/skills': typeof AppSkillsRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/app/admin'
    | '/app/dashboard'
    | '/app/gamification'
    | '/app/interview'
    | '/app/mentor'
    | '/app/readiness'
    | '/app/roadmap'
    | '/app/skills'
    | '/auth/forgot-password'
    | '/auth/sign-in'
    | '/auth/sign-up'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/app/admin'
    | '/app/dashboard'
    | '/app/gamification'
    | '/app/interview'
    | '/app/mentor'
    | '/app/readiness'
    | '/app/roadmap'
    | '/app/skills'
    | '/auth/forgot-password'
    | '/auth/sign-in'
    | '/auth/sign-up'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/app/admin'
    | '/app/dashboard'
    | '/app/gamification'
    | '/app/interview'
    | '/app/mentor'
    | '/app/readiness'
    | '/app/roadmap'
    | '/app/skills'
    | '/auth/forgot-password'
    | '/auth/sign-in'
    | '/auth/sign-up'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthSignInRoute: typeof AuthSignInRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/sign-up': {
      id: '/auth/sign-up'
      path: '/auth/sign-up'
      fullPath: '/auth/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/sign-in': {
      id: '/auth/sign-in'
      path: '/auth/sign-in'
      fullPath: '/auth/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/auth/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/skills': {
      id: '/app/skills'
      path: '/skills'
      fullPath: '/app/skills'
      preLoaderRoute: typeof AppSkillsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/roadmap': {
      id: '/app/roadmap'
      path: '/roadmap'
      fullPath: '/app/roadmap'
      preLoaderRoute: typeof AppRoadmapRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/readiness': {
      id: '/app/readiness'
      path: '/readiness'
      fullPath: '/app/readiness'
      preLoaderRoute: typeof AppReadinessRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/mentor': {
      id: '/app/mentor'
      path: '/mentor'
      fullPath: '/app/mentor'
      preLoaderRoute: typeof AppMentorRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/interview': {
      id: '/app/interview'
      path: '/interview'
      fullPath: '/app/interview'
      preLoaderRoute: typeof AppInterviewRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/gamification': {
      id: '/app/gamification'
      path: '/gamification'
      fullPath: '/app/gamification'
      preLoaderRoute: typeof AppGamificationRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/dashboard': {
      id: '/app/dashboard'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin': {
      id: '/app/admin'
      path: '/admin'
      fullPath: '/app/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppGamificationRoute: typeof AppGamificationRoute
  AppInterviewRoute: typeof AppInterviewRoute
  AppMentorRoute: typeof AppMentorRoute
  AppReadinessRoute: typeof AppReadinessRoute
  AppRoadmapRoute: typeof AppRoadmapRoute
  AppSkillsRoute: typeof AppSkillsRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppGamificationRoute: AppGamificationRoute,
  AppInterviewRoute: AppInterviewRoute,
  AppMentorRoute: AppMentorRoute,
  AppReadinessRoute: AppReadinessRoute,
  AppRoadmapRoute: AppRoadmapRoute,
  AppSkillsRoute: AppSkillsRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthSignInRoute: AuthSignInRoute,
  AuthSignUpRoute: AuthSignUpRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
